### ISSUE TITLE
Arch Linux 下编译后无法运行

### ISSUE THREAD

**Issue by zxp19821005** [biaov/mine-desktop#2]
如题。我下载了最新的发行版[1.0.5](https://github.com/biaov/mine-desktop/archive/refs/tags/v1.0.5.tar.gz)后使用pnpm进行了编译打包，命令如下：
```
$ pnpm install
 WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
 WARN  deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Downloading registry.npmmirror.com/ant-design-vue/3.2.15: 10.1 MB/10.1 MB, done
Packages: +599
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/zxp-endeavouros/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 634, reused 527, downloaded 83, added 599, done
node_modules/.pnpm/core-js@3.31.0/node_modules/core-js: Running postinstall script, done in 112ms
node_modules/.pnpm/robotjs@0.6.0/node_modules/robotjs: Running install script, done in 3s
node_modules/.pnpm/electron@22.0.0/node_modules/electron: Running postinstall script, done in 1.8s

dependencies:
+ @ant-design/icons-vue 6.1.0
+ ant-design-vue 3.2.15 (3.2.20 is available)
+ axios 1.3.2 (1.4.0 is available)
+ moment 2.29.4
+ robotjs 0.6.0
+ vue 3.2.47 (3.3.4 is available)
+ vue-router 4.1.6 (4.2.2 is available)

devDependencies:
+ @electron/rebuild 3.2.10 (3.2.13 is available)
+ @types/node 18.11.19 (20.3.1 is available)
+ @typescript-eslint/eslint-plugin 5.50.0 (5.59.11 is available)
+ @typescript-eslint/parser 5.50.0 (5.59.11 is available)
+ @vitejs/plugin-vue 4.0.0 (4.2.3 is available)
+ cross-env 7.0.3
+ electron 22.0.0 (25.1.0 is available)
+ electron-builder 23.6.0
+ eslint 8.33.0 (8.42.0 is available)
+ eslint-config-airbnb-base 15.0.0
+ eslint-config-prettier 8.6.0 (8.8.0 is available)
+ eslint-plugin-import 2.27.5
+ eslint-plugin-prettier 4.2.1
+ eslint-plugin-vue 9.9.0 (9.14.1 is available)
+ less 4.1.3
+ prettier 2.8.3 (2.8.8 is available)
+ typescript 4.9.5 (5.1.3 is available)
+ vite 4.1.1 (4.3.9 is available)
+ vue-tsc 1.0.24 (1.6.5 is available)

The integrity of 6084 files was checked. This might have caused installation to take longer.
Done in 12.6s
```
```
$ pnpm run build

> mine-desktop@1.0.5 build /home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5
> npm run remove && npm run build:vue && npm run build:app


> mine-desktop@1.0.5 remove
> node script/remove


> mine-desktop@1.0.5 build:vue
> vue-tsc --noEmit && vite build

vite v4.1.1 building for production...
✓ 2633 modules transformed.
dist/resources/vue/index.html                             0.92 kB
dist/resources/vue/assets/logo-6d94f498.svg               1.66 kB
dist/resources/vue/assets/disk02-0d161295.png             5.06 kB
dist/resources/vue/assets/iconfont-f0fe6d07.ttf           5.37 kB
dist/resources/vue/assets/index-a3c0bc61.css              0.22 kB │ gzip:   0.13 kB
dist/resources/vue/assets/index-eb43387e.css              0.22 kB │ gzip:   0.13 kB
dist/resources/vue/assets/index-d71ab9ba.css              0.22 kB │ gzip:   0.13 kB
dist/resources/vue/assets/index-4db6308f.css              0.26 kB │ gzip:   0.16 kB
dist/resources/vue/assets/index-ff2a438c.css              0.33 kB │ gzip:   0.18 kB
dist/resources/vue/assets/index-6868353c.css              0.37 kB │ gzip:   0.19 kB
dist/resources/vue/assets/index-d567b7a7.css              0.39 kB │ gzip:   0.22 kB
dist/resources/vue/assets/index-bd25ab7b.css              5.41 kB │ gzip:   1.28 kB
dist/resources/vue/assets/index-32e2097b.css            613.91 kB │ gzip:  78.60 kB
dist/resources/vue/assets/template-285b0015.js            0.22 kB │ gzip:   0.18 kB
dist/resources/vue/assets/index-f835a961.js               0.49 kB │ gzip:   0.34 kB
dist/resources/vue/assets/index-4e047acb.js               0.52 kB │ gzip:   0.36 kB
dist/resources/vue/assets/index-d817a118.js               0.62 kB │ gzip:   0.44 kB
dist/resources/vue/assets/index-4a21a1c1.js               0.70 kB │ gzip:   0.47 kB
dist/resources/vue/assets/index-947551c2.js               0.80 kB │ gzip:   0.52 kB
dist/resources/vue/assets/index-933e7741.js               1.52 kB │ gzip:   0.90 kB
dist/resources/vue/assets/index-d6bd5669.js               1.74 kB │ gzip:   1.23 kB
dist/resources/vue/assets/index-d2b73005.js               3.08 kB │ gzip:   1.53 kB
dist/resources/vue/assets/index-6054738b.js               7.56 kB │ gzip:   5.10 kB
dist/resources/vue/assets/index-f906ca9e.js             132.34 kB │ gzip:  48.42 kB
dist/resources/vue/assets/ant-design-vue-ce7e2477.js  2,211.97 kB │ gzip: 535.82 kB

(!) Some chunks are larger than 600 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

> mine-desktop@1.0.5 build:app
> node script/build

vite v4.1.1 building for production...
vite v4.1.1 building for production... (x2)
✓ 2 modules transformed.
../dist/resources/app/preload/index.cjs  0.12 kB │ gzip: 0.11 kB
✓ 8 modules transformed.
../dist/resources/app/main/index.cjs  5.63 kB │ gzip: 2.67 kB
```
编译和打包过程没有什么问题，在`dist/package`目录中顺利生成了`linux-unpacked`/`mine-desktop_1.0.5_amd64.snap`/`mine-desktop-1.0.5.AppImage`文件。
直接在终端运行`mine-desktop-1.0.5.AppImage`，报错信息如下：
```
$ ./dist/package/mine-desktop-1.0.5.AppImage 
(node:166606) UnhandledPromiseRejectionWarning: TypeError: i.setAppDetails is not a function
    at w (/tmp/.mount_mine-dEey6wQ/resources/app.asar/dist/resources/app/main/index.cjs:1:5184)
    at /tmp/.mount_mine-dEey6wQ/resources/app.asar/dist/resources/app/main/index.cjs:1:5413
(Use `mine-desktop --trace-warnings ...` to show where the warning was created)
(node:166606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[166606:0613/164719.301960:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
运行`linux-unpacked/mine-desktop`，报错信息如下：
```
$ ./dist/package/linux-unpacked/mine-desktop 
(node:166841) UnhandledPromiseRejectionWarning: TypeError: i.setAppDetails is not a function
    at w (/home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5/dist/package/linux-unpacked/resources/app.asar/dist/resources/app/main/index.cjs:1:5184)
    at /home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5/dist/package/linux-unpacked/resources/app.asar/dist/resources/app/main/index.cjs:1:5413
(Use `mine-desktop --trace-warnings ...` to show where the warning was created)
(node:166841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[166841:0613/164800.842415:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by biaov** [comment]
> 如题。我下载了最新的发行版[1.0.5](https://github.com/biaov/mine-desktop/archive/refs/tags/v1.0.5.tar.gz)后使用pnpm进行了编译打包，命令如下：
> 
> ```
> $ pnpm install
>  WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
>  WARN  deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
>  WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
> Downloading registry.npmmirror.com/ant-design-vue/3.2.15: 10.1 MB/10.1 MB, done
> Packages: +599
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Packages are hard linked from the content-addressable store to the virtual store.
>   Content-addressable store is at: /home/zxp-endeavouros/.local/share/pnpm/store/v3
>   Virtual store is at:             node_modules/.pnpm
> Progress: resolved 634, reused 527, downloaded 83, added 599, done
> node_modules/.pnpm/core-js@3.31.0/node_modules/core-js: Running postinstall script, done in 112ms
> node_modules/.pnpm/robotjs@0.6.0/node_modules/robotjs: Running install script, done in 3s
> node_modules/.pnpm/electron@22.0.0/node_modules/electron: Running postinstall script, done in 1.8s
> 
> dependencies:
> + @ant-design/icons-vue 6.1.0
> + ant-design-vue 3.2.15 (3.2.20 is available)
> + axios 1.3.2 (1.4.0 is available)
> + moment 2.29.4
> + robotjs 0.6.0
> + vue 3.2.47 (3.3.4 is available)
> + vue-router 4.1.6 (4.2.2 is available)
> 
> devDependencies:
> + @electron/rebuild 3.2.10 (3.2.13 is available)
> + @types/node 18.11.19 (20.3.1 is available)
> + @typescript-eslint/eslint-plugin 5.50.0 (5.59.11 is available)
> + @typescript-eslint/parser 5.50.0 (5.59.11 is available)
> + @vitejs/plugin-vue 4.0.0 (4.2.3 is available)
> + cross-env 7.0.3
> + electron 22.0.0 (25.1.0 is available)
> + electron-builder 23.6.0
> + eslint 8.33.0 (8.42.0 is available)
> + eslint-config-airbnb-base 15.0.0
> + eslint-config-prettier 8.6.0 (8.8.0 is available)
> + eslint-plugin-import 2.27.5
> + eslint-plugin-prettier 4.2.1
> + eslint-plugin-vue 9.9.0 (9.14.1 is available)
> + less 4.1.3
> + prettier 2.8.3 (2.8.8 is available)
> + typescript 4.9.5 (5.1.3 is available)
> + vite 4.1.1 (4.3.9 is available)
> + vue-tsc 1.0.24 (1.6.5 is available)
> 
> The integrity of 6084 files was checked. This might have caused installation to take longer.
> Done in 12.6s
> ```
> 
> ```
> $ pnpm run build
> 
> > mine-desktop@1.0.5 build /home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5
> > npm run remove && npm run build:vue && npm run build:app
> 
> 
> > mine-desktop@1.0.5 remove
> > node script/remove
> 
> 
> > mine-desktop@1.0.5 build:vue
> > vue-tsc --noEmit && vite build
> 
> vite v4.1.1 building for production...
> ✓ 2633 modules transformed.
> dist/resources/vue/index.html                             0.92 kB
> dist/resources/vue/assets/logo-6d94f498.svg               1.66 kB
> dist/resources/vue/assets/disk02-0d161295.png             5.06 kB
> dist/resources/vue/assets/iconfont-f0fe6d07.ttf           5.37 kB
> dist/resources/vue/assets/index-a3c0bc61.css              0.22 kB │ gzip:   0.13 kB
> dist/resources/vue/assets/index-eb43387e.css              0.22 kB │ gzip:   0.13 kB
> dist/resources/vue/assets/index-d71ab9ba.css              0.22 kB │ gzip:   0.13 kB
> dist/resources/vue/assets/index-4db6308f.css              0.26 kB │ gzip:   0.16 kB
> dist/resources/vue/assets/index-ff2a438c.css              0.33 kB │ gzip:   0.18 kB
> dist/resources/vue/assets/index-6868353c.css              0.37 kB │ gzip:   0.19 kB
> dist/resources/vue/assets/index-d567b7a7.css              0.39 kB │ gzip:   0.22 kB
> dist/resources/vue/assets/index-bd25ab7b.css              5.41 kB │ gzip:   1.28 kB
> dist/resources/vue/assets/index-32e2097b.css            613.91 kB │ gzip:  78.60 kB
> dist/resources/vue/assets/template-285b0015.js            0.22 kB │ gzip:   0.18 kB
> dist/resources/vue/assets/index-f835a961.js               0.49 kB │ gzip:   0.34 kB
> dist/resources/vue/assets/index-4e047acb.js               0.52 kB │ gzip:   0.36 kB
> dist/resources/vue/assets/index-d817a118.js               0.62 kB │ gzip:   0.44 kB
> dist/resources/vue/assets/index-4a21a1c1.js               0.70 kB │ gzip:   0.47 kB
> dist/resources/vue/assets/index-947551c2.js               0.80 kB │ gzip:   0.52 kB
> dist/resources/vue/assets/index-933e7741.js               1.52 kB │ gzip:   0.90 kB
> dist/resources/vue/assets/index-d6bd5669.js               1.74 kB │ gzip:   1.23 kB
> dist/resources/vue/assets/index-d2b73005.js               3.08 kB │ gzip:   1.53 kB
> dist/resources/vue/assets/index-6054738b.js               7.56 kB │ gzip:   5.10 kB
> dist/resources/vue/assets/index-f906ca9e.js             132.34 kB │ gzip:  48.42 kB
> dist/resources/vue/assets/ant-design-vue-ce7e2477.js  2,211.97 kB │ gzip: 535.82 kB
> 
> (!) Some chunks are larger than 600 kBs after minification. Consider:
> - Using dynamic import() to code-split the application
> - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
> - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
> 
> > mine-desktop@1.0.5 build:app
> > node script/build
> 
> vite v4.1.1 building for production...
> vite v4.1.1 building for production... (x2)
> ✓ 2 modules transformed.
> ../dist/resources/app/preload/index.cjs  0.12 kB │ gzip: 0.11 kB
> ✓ 8 modules transformed.
> ../dist/resources/app/main/index.cjs  5.63 kB │ gzip: 2.67 kB
> ```
> 
> 编译和打包过程没有什么问题，在`dist/package`目录中顺利生成了`linux-unpacked`/`mine-desktop_1.0.5_amd64.snap`/`mine-desktop-1.0.5.AppImage`文件。 直接在终端运行`mine-desktop-1.0.5.AppImage`，报错信息如下：
> 
> ```
> $ ./dist/package/mine-desktop-1.0.5.AppImage 
> (node:166606) UnhandledPromiseRejectionWarning: TypeError: i.setAppDetails is not a function
>     at w (/tmp/.mount_mine-dEey6wQ/resources/app.asar/dist/resources/app/main/index.cjs:1:5184)
>     at /tmp/.mount_mine-dEey6wQ/resources/app.asar/dist/resources/app/main/index.cjs:1:5413
> (Use `mine-desktop --trace-warnings ...` to show where the warning was created)
> (node:166606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [166606:0613/164719.301960:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
> ```
> 
> 运行`linux-unpacked/mine-desktop`，报错信息如下：
> 
> ```
> $ ./dist/package/linux-unpacked/mine-desktop 
> (node:166841) UnhandledPromiseRejectionWarning: TypeError: i.setAppDetails is not a function
>     at w (/home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5/dist/package/linux-unpacked/resources/app.asar/dist/resources/app/main/index.cjs:1:5184)
>     at /home/zxp-endeavouros/.cache/paru/clone/mine-desktop-1.0.5/dist/package/linux-unpacked/resources/app.asar/dist/resources/app/main/index.cjs:1:5413
> (Use `mine-desktop --trace-warnings ...` to show where the warning was created)
> (node:166841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [166841:0613/164800.842415:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
> ```

抱歉，目前只支持 windows 环境
